version: '3.4'

x-common-env-vars:
  - &postgres-url
    "BALLSDEXBOT_DB_URL=postgres://ballsdex:${POSTGRES_PASSWORD}@postgres:5432/ballsdex"

services:

  bot:
    restart: "no"
    image: ballsdex
    build: .
    environment:
      - *postgres-url
      - BALLSDEXBOT_TOKEN
    depends_on:
      - postgres-db
    volumes:
      - bot-static:/code/static/uploads
    command: poetry run python3 -m ballsdex --dev --disable-rich

  admin-panel:
    image: ballsdex
    ports:
      - "8000:8000"
    environment:
      - *postgres-url
      - "BALLSDEXBOT_REDIS_URL=redis://redis"
    depends_on:
      - bot
      - postgres-db
      - redis-cache
    volumes:
      - bot-static:/code/static/uploads
    command: poetry run uvicorn ballsdex.core.admin:_app --host 0.0.0.0

  postgres-db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=ballsdex
      - POSTGRES_DB=ballsdex
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:  # Persist the db data
      - database-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache-data:/data

volumes:
  bot-static:
  database-data:
  cache-data: