services:

  bot:
    restart: "no"
    build: .
    ports:
      - "8000:8000"
    environment:
      - BALLSDEXBOT_TOKEN
      - "BALLSDEXBOT_DB_URL=postgres://ballsdex:${POSTGRES_PASSWORD}@postgres:5432/ballsdex"
      - "BALLSDEXBOT_REDIS_URL=redis://redis"
    depends_on:
      - db
      - redis-cache
    volumes:
      - bot-static:/code/static/uploads

  db:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=ballsdex
      - POSTGRES_DB=ballsdex
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:  # Persist the db data
      - database-data:/var/lib/postgresql/data

  redis-cache:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache-data:/data

volumes:
  bot-static:
  database-data:
  cache-data: