[tool.poetry]
name = "ballsdex"
version = "1.0.0a1"
description = ""
authors = ["laggron42 <laggron42@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

# asyncio
uvloop = { version = "^0.16.0", markers = "sys_platform != 'win32'" }

# discord
"discord.py" = "^2.0.1"

# fastapi
fastapi = "^0.82.0"
fastapi-admin = {git = "https://github.com/fastapi-admin/fastapi-admin", rev = "5f34bf0d7356afa4c6034a7ab3942ea843d3b8ce"}
uvicorn = "^0.18.3"

# database ORM
tortoise-orm = {extras = ["asyncpg"], version = "^0.19.2"}
aioredis = "^2.0.1"

# misc
rich = "^12.5.1"
python-dateutil = "^2.8.2"
Pillow = "^9.2.0"
aerich = "^0.6.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = {version = "^22.10.0", allow-prereleases = true}


[tool.poetry.group.metrics.dependencies]
prometheus-client = "^0.15.0"

[tool.aerich]
tortoise_orm = "ballsdex.__main__.TORTOISE_ORM"
location = "./migrations"
src_folder = "./ballsdex"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
    line-length = 99
    target-version = ['py38']
    include = '\.py$'

[tool.flake8]
    ignore = "W503,E203"
    max-line-length = 99
