name: Docker build

on:
  push:
  pull_request:

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    name: Docker build and push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker hub
        uses: docker/build-push-action@v2
        with:
          tags: "ghcr.io/laggron42/ballsdex:${{ github.sha }}"
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
